name: ngs_data_charmer
channels:
  - anaconda
  - agbiome
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - aioeasywebdav=2.4.0=py38h32f6830_1001
  - aiohttp=3.6.2=py38h1e0a361_1
  - alsa-lib=1.2.3=h516909a_0
  - amply=0.1.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - atk=2.36.0=3
  - atk-1.0=2.36.0=h63f31ab_3
  - attrs=20.2.0=pyh9f0ad1d_0
  - bbtools=37.62=0
  - bcrypt=3.2.0=py38h1e0a361_1
  - bedtools=2.29.2=hc088bd4_0
  - binutils_impl_linux-64=2.35=h18a2f87_9
  - binutils_linux-64=2.35=hc3fd857_29
  - biopython=1.78=py38h1e0a361_1
  - boto3=1.16.2=pyh9f0ad1d_0
  - botocore=1.19.2=pyh9f0ad1d_0
  - bowtie2=2.4.2=py38h1c8e9b9_0
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=h488836b_1006
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.3=py38h1bdcb99_1
  - chardet=3.0.4=py38h924ce5b_1008
  - click=7.1.2=pyh9f0ad1d_0
  - coincbc=2.10.5=h71b4bd6_1
  - coloredlogs=14.0=py38h32f6830_2
  - colormath=3.0.0=py_2
  - configargparse=1.2.3=pyh9f0ad1d_0
  - cryptography=3.1.1=py38hb23e4d4_1
  - curl=7.71.1=he644dc0_8
  - cutadapt=2.10=py38h0213d0e_1
  - cycler=0.10.0=py_2
  - datrie=0.8.2=py38h1e0a361_1
  - decorator=4.4.2=py_0
  - deeptools=3.5.0=py_0
  - deeptoolsintervals=0.1.9=py38h0213d0e_2
  - dnaio=0.4.2=py38h0213d0e_1
  - docutils=0.16=py38h924ce5b_2
  - dropbox=10.4.1=pyh9f0ad1d_0
  - expat=2.2.9=he1b5a44_2
  - fastqc=0.11.9=0
  - fftw=3.3.8=nompi_hdcdd268_1112
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h1056068_1002
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=he06d7ca_0
  - fribidi=1.0.10=h516909a_0
  - ftputil=4.0.0=py_0
  - future=0.18.2=py38h32f6830_2
  - gcc_impl_linux-64=9.3.0=h28f5a38_17
  - gcc_linux-64=9.3.0=h7247604_29
  - gdk-pixbuf=2.38.2=h3f25603_5
  - gettext=0.19.8.1=hf34092f_1004
  - gfortran_impl_linux-64=9.3.0=h2bb4189_17
  - gfortran_linux-64=9.3.0=ha1c937c_29
  - ghostscript=9.53.3=he1b5a44_1
  - giflib=5.2.1=h516909a_2
  - gitdb=4.0.5=py_0
  - gitpython=3.1.9=py_0
  - glib=2.66.2=he1b5a44_0
  - gmap=2020.10.14=pl526h2f06484_0
  - gobject-introspection=1.66.1=py38he66682d_2
  - google-api-core=1.22.4=pyh9f0ad1d_0
  - google-api-python-client=1.12.4=pyh9f0ad1d_0
  - google-auth=1.22.0=py_0
  - google-auth-httplib2=0.0.4=pyh9f0ad1d_0
  - google-cloud-core=1.4.3=pyh9f0ad1d_0
  - google-cloud-storage=1.31.2=pyh9f0ad1d_0
  - google-crc32c=1.0.0=py38h6d3b9ce_1
  - google-resumable-media=1.1.0=pyh9f0ad1d_0
  - googleapis-common-protos=1.52.0=py38h32f6830_0
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.42.3=h6939c30_2
  - grpcio=1.31.0=py38h2c89da0_0
  - gsl=2.6=h294904e_0
  - gtk2=2.24.32=h194ddfc_3
  - gts=0.7.6=h17b2bb4_1
  - gxx_impl_linux-64=9.3.0=h53cdd4c_17
  - gxx_linux-64=9.3.0=h0d07fa4_29
  - harfbuzz=2.7.2=hb1ce69c_1
  - hisat2=2.2.1=he1b5a44_2
  - htslib=1.11=hd3b49d5_0
  - httplib2=0.18.1=pyh9f0ad1d_0
  - humanfriendly=8.2=py38h32f6830_1
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - igvtools=2.5.3=0
  - imagemagick=7.0.10_28=pl526h201ca68_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipython_genutils=0.2.0=py_1
  - java-jdk=7.0.91=1
  - jbig=2.1=h516909a_2002
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py_2
  - jupyter_core=4.6.3=py38h32f6830_2
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - kiwisolver=1.2.0=py38hbf85e49_1
  - krb5=1.17.1=hfafb76e_3
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcrc32c=1.1.1=he1b5a44_2
  - libcurl=7.71.1=hcdd3856_8
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-devel_linux-64=9.3.0=hfd08b2a_17
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libglib=2.66.2=h0dae87d_0
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_h4812303_5
  - libpng=1.6.37=hed695b0_2
  - libprotobuf=3.13.0.1=h8b12597_0
  - librsvg=2.50.1=h33a7fed_0
  - libsodium=1.0.18=h516909a_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-devel_linux-64=9.3.0=h4084dd6_17
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=hc7e4089_6
  - libtool=2.4.6=hebb1f50_1006
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.1.0=h56121f0_4
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - lzstring=1.0.4=py_1001
  - make=4.3=hd18ef5c_1
  - markdown=3.3.2=pyh9f0ad1d_0
  - markupsafe=1.1.1=py38h8df0ef7_2
  - matplotlib-base=3.3.2=py38h4d1ce4f_1
  - multidict=4.7.5=py38h1e0a361_2
  - multiqc=1.9=py_1
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he1b5a44_2
  - networkx=2.5=py_0
  - numpy=1.19.2=py38hf89b668_1
  - oauth2client=4.1.3=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjdk=8.0.152=h7b6447c_3
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1i=h7f98852_0
  - pandas=1.1.3=py38hddd6c8b_2
  - pango=1.42.4=h80147aa_5
  - paramiko=2.7.2=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - pcre2=10.35=h2f06484_0
  - perl=5.26.2=h516909a_1006
  - picard=2.23.8=0
  - pigz=2.3.4=hed695b0_1
  - pillow=8.0.0=py38h9776b28_0
  - pip=20.2.4=py_0
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h516909a_1008
  - plotly=4.11.0=pyh9f0ad1d_0
  - prettytable=0.7.2=py_3
  - protobuf=3.13.0.1=py38h950e882_1
  - psutil=5.7.2=py38h8df0ef7_1
  - pthread-stubs=0.4=h14c3975_1001
  - pulp=2.3.1=py38h32f6830_0
  - py2bit=0.3.0=py38h0213d0e_4
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybigwig=0.3.17=py38h55f8d50_2
  - pybktree=1.1=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.1=py_0
  - pygraphviz=1.6=py38h25c7686_1
  - pynacl=1.4.0=py38h1e0a361_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h1e0a361_1
  - pysam=0.16.0.1=py38hbdc2ae9_1
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py38h924ce5b_2
  - python=3.8.6=h852b56e_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.8.2=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py38h8df0ef7_1
  - r-base=4.0.3=hc603457_2
  - ratelimiter=1.2.0=py_1002
  - readline=8.0=he28a2e2_2
  - regex=2020.11.13=py38h497a2fe_1
  - requests=2.24.0=pyh9f0ad1d_0
  - retrying=1.3.3=py_2
  - rsa=4.6=pyh9f0ad1d_0
  - s3transfer=0.3.3=py_3
  - samtools=1.11=h6270b1f_0
  - scipy=1.5.2=py38hd648e70_2
  - sed=4.8=hbfbb72e_0
  - setuptools=49.6.0=py38h924ce5b_2
  - simplejson=3.17.2=py38h1e0a361_1
  - six=1.15.0=pyh9f0ad1d_0
  - slacker=0.14.0=py_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snakemake=5.26.1=1
  - snakemake-minimal=5.26.1=py_1
  - spectra=0.0.11=py_1
  - sqlite=3.33.0=h4cf870e_1
  - subread=2.0.1=hed695b0_0
  - sysroot_linux-64=2.12=h77966d4_13
  - tbb=2020.2=hc9558a2_0
  - tk=8.6.10=hed695b0_1
  - tktable=2.10=h555a92e_3
  - toposort=1.5=py_3
  - tornado=6.0.4=py38h1e0a361_2
  - traitlets=5.0.5=py_0
  - trim-galore=0.6.6=0
  - umi_tools=1.1.1=py38h0213d0e_1
  - uritemplate=3.0.1=py_0
  - urllib3=1.25.11=py_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - wrapt=1.12.1=py38h1e0a361_1
  - xmlrunner=1.7.7=py_0
  - xopen=0.9.0=py38h32f6830_1
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.2=py38h1e0a361_0
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2

